[package]
name = "shared-network"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../../lib/base" }
network = { path = "../../lib/network" }
pool = { path = "../../lib/pool" }

shared-base = { path = "../shared-base" }
game-interface = { path = "../game-interface" }

bincode = { features = ["serde"], version = "2.0.0-rc.3" }
async-trait = "0.1.81"
serde = "1.0.208"
tokio = { version = "1.39.3", features = ["rt-multi-thread", "sync", "time", "macros"] }
log = "0.4.22"
