[package]
name = "shared-network"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../../lib/base" }
shared-base = { path = "../shared-base" }
game-interface = { path = "../game-interface" }
network = { path = "../../lib/network" }
pool = { path = "../../lib/pool" }
bincode = { features = ["serde"], version = "2.0.0-rc.3" }
async-trait = "0.1.80"
serde = "1.0.198"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "sync", "time", "macros"] }
ed25519-dalek = { version = "2.1.1", features = ["serde"] }
