[package]
name = "shared-network"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../../lib/base" }
shared-base = { path = "../shared-base" }
shared-game = { path = "../shared-game" }
network = { path = "../../lib/network" }
pool = { path = "../../lib/pool" }
bincode = { features = ["serde"], version = "2.0.0-rc.3" }
async-trait = "0.1.73"
serde = "1.0.187"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "sync", "time", "macros"] }
