[package]
name = "client-types"
version = "0.1.0"
edition = "2021"

[dependencies]
pool = { path = "../../lib/pool" }
config = { path = "../../lib/config" }
shared-base = { path = "../shared-base" }
game-config = { path = "../game-config" }
bincode = { features = ["serde"], version = "2.0.0-rc.3" }
serde = "1.0.193"
serde_with = "3.4.0"
anyhow = "1.0.75"
