CREATE TABLE record_teamrace (
    Map VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    Name VARCHAR(16) COLLATE utf8mb4_bin NOT NULL,
    Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Time FLOAT DEFAULT 0,
    ID VARBINARY(16) NOT NULL,
    GameId VARCHAR(64),
    DDNet7 BOOL DEFAULT FALSE,
    PRIMARY KEY (Id, Name)
);
