[package]
name = "binds"
version = "0.1.0"
edition = "2021"

[dependencies]
game-interface = { path = "../game-interface" }
client-types = { path = "../client-types" }

native = { path = "../../lib/native" }

serde_json = "1.0.116"
anyhow = { version = "1.0.82", features = ["backtrace"] }
