[package]
name = "server-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
network = { path = "../../lib/network" }
base = { path = "../../lib/base" }
server = { path = "../../game/server", default-features = false }
shared-base = { path = "../../game/shared-base" }
game-config = { path = "../../game/game-config" }

clap = { version = "4.5.16", features = ["derive", "cargo"] }
serde_json = "1.0.125"
env_logger = "0.11.5"

[features]
legacy = ["server/legacy"]

default = ["legacy"]
