[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
base-io = { path = "../../../lib/base-io" }
base-fs-traits = { path = "../../../lib/base-fs-traits" }
base-log = { path = "../../../lib/base-log" }
api = { path = "../../../lib/api" }
api-ui = { path = "../../../lib/api-ui" }
graphics-types = { path = "../../../lib/graphics-types" }
graphics-base = { path = "../../../lib/graphics-base" }
ui-base = { path = "../../../lib/ui-base" }
ui-traits = { path = "../../../lib/ui-traits" }
client-ui = { path = "../../../game/client-ui" }
client-types = { path = "../../../game/client-types" }
client-containers = { path = "../../../game/client-containers" }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
egui = { version = "0.22.0", features = ["serde"] }
egui_extras = "0.22.0"

[lib]
crate-type = ["cdylib"]
