[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../../../lib/api" }
api-ui = { path = "../../../lib/api-ui" }
graphics-types = { path = "../../../lib/graphics-types" }
graphics-base = { path = "../../../lib/graphics-base" }
ui-base = { path = "../../../lib/ui-base" }
ui-traits = { path = "../../../lib/ui-traits" }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
egui = { version = "0.22.0", features = ["serde"] }

[lib]
crate-type = ["cdylib"]
