[package]
name = "actionfeed"
version = "0.1.0"
edition = "2021"

[dependencies]
math = { path = "../../../lib/math" }
base-io = { path = "../../../lib/base-io" }
base-io-traits = { path = "../../../lib/base-io-traits" }
base-log = { path = "../../../lib/base-log" }
api = { path = "../../../lib/api" }
api-ui = { path = "../../../lib/api-ui" }
graphics-types = { path = "../../../lib/graphics-types" }
graphics = { path = "../../../lib/graphics" }
ui-base = { path = "../../../lib/ui-base" }
ui-traits = { path = "../../../lib/ui-traits" }
api-ui-game = { path = "../../../game/api-ui-game" }
client-ui = { path = "../../../game/client-ui" }
client-render-base = { path = "../../../game/client-render-base" }
client-types = { path = "../../../game/client-types" }
client-containers = { path = "../../../game/client-containers" }
game-interface = { path = "../../../game/game-interface" }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
egui = { version = "0.27.2", features = ["serde"] }
egui_extras = "0.27.2"

[lib]
crate-type = ["cdylib"]
