[package]
name = "prediction_timer_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
math = { path = "../../../lib/math" }
base-io = { path = "../../../lib/base-io" }
base-io-traits = { path = "../../../lib/base-io-traits" }
base-log = { path = "../../../lib/base-log" }
api = { path = "../../../lib/api" }
api-ui = { path = "../../../lib/api-ui" }
graphics-types = { path = "../../../lib/graphics-types" }
graphics = { path = "../../../lib/graphics" }
ui-base = { path = "../../../lib/ui-base" }
ui-traits = { path = "../../../lib/ui-traits" }

api-ui-game = { path = "../../../game/api-ui-game" }
client-ui = { path = "../../../game/client-ui" }
client-render-base = { path = "../../../game/client-render-base" }
client-types = { path = "../../../game/client-types" }
client-containers = { path = "../../../game/client-containers" }
game-interface = { path = "../../../game/game-interface" }
prediction-timer = { path = "../../../game/prediction-timer" }

bincode = { version = "2.0.0-rc.3", features = ["serde"] }
egui = { git = "https://github.com/emilk/egui", rev = "9a1e358a144b5d2af9d03a80257c34883f57cf0b", features = ["serde"] }
egui_extras = { git = "https://github.com/emilk/egui", rev = "9a1e358a144b5d2af9d03a80257c34883f57cf0b" }
egui_plot = { git = "https://github.com/emilk/egui_plot", rev = "d00fa85a84f4d443e2803b5185e230be56da123f" }

[lib]
crate-type = ["cdylib"]
