[package]
name = "account-server"
version = "0.1.0"
edition = "2021"

[dependencies]
accounts-base = { path = "../../lib/accounts-base" }
account-sql = { path = "../../lib/account-sql" }

tokio = { version = "1.37.0", features = ["rt-multi-thread", "sync", "fs", "time", "macros"] }
axum = "0.7.5"
anyhow = { version = "1.0.82", features = ["backtrace"] }
sqlx = { version = "0.7.4", features = ["mysql", "runtime-tokio"] }
email_address = { version = "0.2.4", features = ["serde"] }
ed25519-dalek = { version = "2.1.1", features = ["serde"] }
async-trait = "0.1.80"
argon2 = "0.5.3"
serde_json = "1.0.116"
parking_lot = "0.12.2"
lettre = "0.11.7"
serde = { version = "1.0.198", features = ["derive"] }
base64 = "0.22.1"
url = { version = "2.5.0", features = ["serde"] }
log = "0.4.21"
clap = { version = "4.5.4", features = ["derive", "cargo"] }
env_logger = "0.11.3"

[dev-dependencies]
account-client = { path = "../../lib/account-client" }
account-game-server = { path = "../../lib/account-game-server" }
client-reqwest = { path = "../../lib/client-reqwest" }

regex = "1.10.4"
tempfile = "3.10.1"
reqwest = { version = "0.12.4" }
