[target.'cfg(target_env = "msvc")']
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-gnu]
rustflags = [ "-C", "link-arg=-lssp" ]

[target.i686-pc-windows-gnu]
rustflags = [ "-C", "link-arg=-lssp" ]

[target.aarch64-linux-android]
rustflags = [
    "-C", "link-arg=-lc++_static",
    "-C", "link-arg=-lc++abi",
    "-C", "link-arg=-lstdc++"
]

[target.'cfg(target_arch = "wasm32")']
rustflags = [
    "-C", "target-feature=+simd128"
]
