[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../../../lib/api" }
api-macros = { path = "../../../lib/api-macros" }
base-io = { path = "../../../lib/base-io" }
math = { path = "../../../lib/math" }
base = { path = "../../../lib/base" }
base-log = { path = "../../../lib/base-log" }
graphics-types = { path = "../../../lib/graphics-types" }
pool = { path = "../../../lib/pool" }
hiarc = { path = "../../../lib/hiarc", features = ["derive", "enable_hashlink", "enable_rustc_hash"] }
api-wasm-macros = { path = "../../../lib/api-wasm-macros" }
game-database = { path = "../../../lib/game-database" }

api-state = { path = "../../../game/api-state" }
shared-base = { path = "../../../game/shared-base" }
shared-game = { path = "../../../game/shared-game" }
game-interface = { path = "../../../game/game-interface" }
map = { path = "../../../game/map" }
command-parser = { path = "../../../game/command-parser" }

rayon = "1.10.0"
arrayvec = { version = "0.7.6", features = ["serde"] }
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
bincode = { features = ["serde"], version = "2.0.0-rc.3" }
flate2 = "1.0.31"
anyhow = { version = "1.0.86", features = ["backtrace"] }
async-trait = "0.1.81"
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "pr-skipped-it", features = ["serde", "serde_impl"] }
serde = "1.0.208"
thiserror = "1.0.63"
log = "0.4.22"
chrono = { version = "0.4.38", default-features = false, features = ["serde"] }
serde_json = "1.0.125"
rustc-hash = "2.0.0"

[lib]
crate-type = ["cdylib"]
