[package]
name = "shared-base"
version = "0.1.0"
edition = "2021"

[dependencies]
math = { path = "../../lib/math" }
base = { path = "../../lib/base" }
graphics-types = { path = "../../lib/graphics-types" }
pool = { path = "../../lib/pool" }
api-wasm-macros = { path = "../../lib/api-wasm-macros" }
rayon = "1.7.0"
arrayvec = { version = "0.7.4", features = ["serde"] }
num = "0.4.1"
num-derive = "0.4.0"
num-traits = "0.2.16"
bincode = { features = ["serde"], version = "2.0.0-rc.3" }
flate2 = "1.0.27"
anyhow = "1.0.75"
async-trait = "0.1.73"
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "pr-skipped-it", features = ["serde", "serde_impl"] }
serde = "1.0.187"
indexmap = "2.0.0"
thiserror = "1.0.47"
tinyvec = { version = "1.6.0", features = ["serde"] }
