pub const TABLE_COLUMN_POINTS_WIDTH: f32 = 40.0;
pub const TABLE_COLUMN_TEE_WIDTH: f32 = 15.0;
pub const TABLE_COLUMN_NAME_WIDTH: f32 = 100.0;
pub const TABLE_COLUMN_CLAN_WIDTH: f32 = 80.0;
pub const TABLE_COLUMN_FLAG_WIDTH: f32 = 40.0;
pub const TABLE_COLUMN_PING_WIDTH: f32 = 30.0;

pub const TABLE_COLUMNS: [f32; 6] = [
    TABLE_COLUMN_POINTS_WIDTH,
    TABLE_COLUMN_TEE_WIDTH,
    TABLE_COLUMN_NAME_WIDTH,
    TABLE_COLUMN_CLAN_WIDTH,
    TABLE_COLUMN_FLAG_WIDTH,
    TABLE_COLUMN_PING_WIDTH,
];
