[package]
name = "map-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../../lib/base" }
base-io = { path = "../../lib/base-io" }
base-fs = { path = "../../lib/base-fs" }
map = { path = "../../game/map" }
map-convert-lib = { path = "../../game/map-convert-lib" }
clap = { version = "4.5.4", features = ["derive"] }
rayon = "1.10.0"
anyhow = { version = "1.0.82", features = ["backtrace"] }
