[package]
name = "master-server"
version = "0.1.0"
edition = "2021"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
publish = false
license = "Zlib"

[dependencies]
master-server-types = { path = "../../game/master-server-types" }
arrayvec = { version = "0.5.2", features = ["serde"] }
base64 = "0.13.1"
bytes = "1.5.0"
clap = { version = "2.34.0", default-features = false, features = [
  "suggestions",
  "wrap_help",
] }
csv = "1.3.0"
env_logger = "0.8.4"
headers = "0.3.9"
hex = "0.4.3"
ipnet = { version = "2.9.0", features = ["serde"] }
log = "0.4.20"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108", features = [
  "float_roundtrip",
  "preserve_order",
  "raw_value",
] }
sha2 = "0.10.8"
tokio = { version = "1.35.0", features = ["macros", "rt", "rt-multi-thread"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
url = { version = "2.5.0", features = ["serde"] }
warp = { version = "0.3.6", default-features = false }

