[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
math = { path = "../../lib/math" }
base = { path = "../../lib/base" }
network = { path = "../../lib/network" }
shared-base = { path = "../shared-base" }
shared-game = { path = "../shared-game" }
shared-network = { path = "../shared-network" }
shared = { path = "../shared" }
config = { path = "../../lib/config" }
config-fs = { path = "../../lib/config-fs" }
base-fs = { path = "../../lib/base-fs" }
pool = { path = "../../lib/pool" }
rayon = "1.7.0"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "sync", "fs", "time", "macros"] }
rcgen = "0.11.1"
arrayvec = "0.7.4"
hashlink = { version = "0.8.3", features = ["serde"] }
thiserror = "1.0.40"
