[package]
name = "game-config"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../../lib/config" }
config-macro = { path = "../../lib/config-macro" }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
anyhow = "1.0.75"
