[package]
name = "client-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
client-types = { path = "../client-types" }
client-containers = { path = "../client-containers" }
client-render-base = { path = "../client-render-base" }
master-server-types = { path = "../master-server-types" }
shared-base = { path = "../shared-base" }
shared-game = { path = "../shared-game" }
game-config = { path = "../game-config" }
base-log = { path = "../../lib/base-log" }
base-io = { path = "../../lib/base-io" }
config = { path = "../../lib/config" }
ui-base = { path = "../../lib/ui-base" }
ui-traits = { path = "../../lib/ui-traits" }
math = { path = "../../lib/math" }
graphics = { path = "../../lib/graphics" }
graphics-types = { path = "../../lib/graphics-types" }
graphics-backend-traits = { path = "../../lib/graphics-backend-traits" }
egui = { version = "0.23.0", features = ["serde"] }
egui_extras = "0.23.0"
fuzzy-matcher = "0.3.7"
serde_json = "1.0.108"
